language: node_js
node_js:
  - 12.18
scripts:
  - npm run test
  - npm run deploy
deploy:
  provider: lambda
  function_name: "cs3219-api"
  region: "us-east-2"
  role: "arn:aws:iam::983644291011:role/service-role/cs3219-api-role-1wmov5dr"
  runtime: "nodejs12.x"
  handler_name: "handler"
